cargo-features = ["edition2021"]

[package]
name = "cliff"
version = "0.1.0"
authors = ["chedim"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[dev-dependencies]
mockall = "0.9.1"
mockall_double = "0.2.0"
